import getChapterCount from '../../src/lib/getChapterCount.ts';
import getJsonBookByName from '../../src/lib/getJsonBookByName.ts';
import getJsonWorkByName from '../../src/lib/getJsonWorkByName.ts';
import getVerseCounts from '../../src/lib/getVerseCounts.ts';
import type {
  BookShape,
  WorkShape,
} from '../../src/types/data-shapes.ts';

const s = (v:any) => JSON.stringify(v, null, 2);

const u = (s: string) => s.toUpperCase();

main().catch(console.error);

async function main() {
  const versesDir = `${import.meta.dir}/../../data/verses`;
  const tsDest = Bun.file(
    `${import.meta.dir}/../../data/compiled/books-and-works.ts`,
  );
  const jsonDest = Bun.file(
    `${import.meta.dir}/../../data/compiled/books-and-works.json`,
  );
  const glob = new Bun.Glob('*.json');
  const works: WorkShape[] = [];
  const books: BookShape[] = [];
  const chapterCounts: Record<string, number> = {};
  const verseCounts: Record<string, number[]> = {};
  const worksLookup: Record<string, number> = {};
  const booksLookup: Record<string, number> = {};
  const groupsLookup: Record<string, number[]> = {};
  const seenBooks: string[] = [];
  for await (const file of glob.scan(versesDir)) {
    const data = await Bun.file(`${versesDir}/${file}`).json();
    const name = file.replace('.json', '');
    const work = getJsonWorkByName(name);
    if (!work) {
      throw new Error(`Unrecognized work "${name}"`);
    }
    works.push(work);
    for (const verse of data.verses) {
      if (seenBooks.includes(verse.bookOsisID)) {
        continue;
      }
      seenBooks.push(verse.bookOsisID);
      const book = getJsonBookByName(verse.bookOsisID);
      if (!book) {
        throw new Error(
          `Unrecognized book "${verse.bookOsisID}" in work "${name}"`,
        );
      }
      books.push(book);
    }
    for (const book of books) {
      if (book.workOsisID === work.workOsisID) {
        chapterCounts[book.bookOsisID] = getChapterCount(
          book.bookOsisID,
          data.verses,
        );
        verseCounts[book.bookOsisID] = getVerseCounts(
          book.bookOsisID,
          data.verses,
        );
      }
    }
  }
  works.sort((a,b) => a.workOsisID.localeCompare(b.workOsisID));

  const jsonData = {
    works,
    books,
    chapterCounts,
    verseCounts,
    worksLookup,
    booksLookup,
    groupsLookup,
  };
  const addWork = (s:string,i:number) => {
    const up = u(s);
    if (up in worksLookup) {
      throw new Error(`Duplicate work alias ${s}!`);
    }
    worksLookup[up] = i;
  }
  for (let i = 0; i < works.length; i++) {
    const work = works[i];
    addWork(work.workOsisID,i);
    if (work.workOsisID !== work.workTitle) {
      addWork(work.workTitle,i);
    }
    for (const alias of work.aliases) {
      addWork(alias,i);
    }
  }
  const addBook = (s:string,i:number) => {
    const up = u(s);
    if (up in booksLookup) {
      throw new Error(`Duplicate book alias ${s}!`);
    }
    booksLookup[up] = i;
  }
  for (let i = 1; i < books.length; i++) {
    const book = books[i];
    addBook(book.bookOsisID,i);
    if (book.bookOsisID !== book.bookName) {
      addBook(book.bookName,i);
    }
    if (book.paratext && book.paratext !== u(book.bookOsisID) && book.paratext !== u(book.bookName)) {
      addBook(book.paratext,i);
    }
    for (const alias of book.aliases) {
      addBook(alias,i);
    }
    for (const group of book.groups) {
      const uGroup = u(group);
      if (!(uGroup in groupsLookup)) {
        groupsLookup[uGroup] = [] as number[];
      }
      groupsLookup[uGroup].push(i);
    }
  }
  await jsonDest.write(JSON.stringify(jsonData, null, 2));
  console.log(`Wrote ${jsonDest.size} bytes to jsDest`);

    const output = [];

    // works
    output.push(`// Auto-generated on ${new Date().toISOString()}`);
    output.push(`// DO NOT EDIT THIS FILE`);
    output.push(
      `
import type {
  BookShape,
  WorkShape,
} from '../../src/types/data-shapes.ts';
  `.trim(),
    );
    output.push(`export const works : WorkShape[] = ${s(works)};`);
    output.push(`export const books : BookShape[] = ${s(books)};`);
    output.push(`export const chapterCounts : Record<string, number> = ${s(chapterCounts)};`);
    output.push(`export const verseCounts : Record<string, number[]> = ${s(verseCounts)};`);
    output.push(`export const worksLookup : Record<string, number> = ${s(worksLookup)};`);
    output.push(`export const booksLookup : Record<string, number> = ${s(booksLookup)};`);
    output.push(`export const groupsLookup : Record<string, number[]> = ${s(groupsLookup)};`);
    await tsDest.write(output.join('\n'));
    console.log(`wrote ${tsDest.size} bytes of typed data to tsDest`);
}
