// Auto-generated on 2025-11-04T18:39:05.810Z
// DO NOT EDIT THIS FILE
import type {
  BookShape,
  WorkShape,
  VerseShape,
  AnalysisShape,
  VerseDataFileShape,
} from '../../src/types/data-shapes.ts';
export const works : WorkShape[] = [
  {
    "workOsisID": "KJVA",
    "workTitle": "The Holy Bible Apocrypha",
    "workSubtitle": "King James Version",
    "aliases": [
      "King James Apocrypha"
    ]
  },
  {
    "workOsisID": "T12Patr",
    "workTitle": "Testaments of the Twelve Patriarchs",
    "workSubtitle": "",
    "aliases": [
      "The Testaments of the Twelve Patriarchs",
      "The Testament of the Twelve Patriarchs",
      "The Testament of the 12 Patriarchs",
      "Testament of the Twelve Patriarchs",
      "Testament of the 12 Patriarchs",
      "Testaments of the 12 Patriarchs",
      "12 Patriarchs",
      "The 12 Patriarchs",
      "The Twelve Patriarchs",
      "T 12 Patriarchs",
      "12 Patr"
    ]
  },
  {
    "workOsisID": "Didache",
    "workTitle": "Didache",
    "workSubtitle": "The Lord's Teaching Through the Twelve Apostles to the Nations",
    "aliases": [
      "The Didache"
    ]
  },
  {
    "workOsisID": "BofM",
    "workTitle": "The Book of Mormon",
    "workSubtitle": "Another Testament of Jesus Christ",
    "aliases": [
      "BOM",
      "Book of Mormon"
    ]
  },
  {
    "workOsisID": "PGP",
    "workTitle": "Pearl of Great Price",
    "workSubtitle": "of The Church of Jesus Christ of Latter-day Saints",
    "aliases": [
      "The Pearl of Great Price",
      "PGoP"
    ]
  },
  {
    "workOsisID": "D&C",
    "workTitle": "Doctrine and Covenants",
    "workSubtitle": "of The Church of Jesus Christ of Latter-day Saints",
    "aliases": [
      "D and C",
      "The Doctrine & Covenants",
      "Doctrine & Covenants",
      "The Doctrine and Covenants"
    ]
  },
  {
    "workOsisID": "Fathers",
    "workTitle": "Apostolic Fathers",
    "workSubtitle": "Translated by J.  B. Lightfoot",
    "aliases": [
      "The Apostolic Fathers"
    ]
  }
];
const w = works;
export const worksLookup : Record<string, (typeof w)[number]> = {
  "THE HOLY BIBLE APOCRYPHA": w[0],
  "KJVA": w[0],
  "KING JAMES APOCRYPHA": w[0],
  "TESTAMENTS OF THE TWELVE PATRIARCHS": w[1],
  "T12PATR": w[1],
  "THE TESTAMENTS OF THE TWELVE PATRIARCHS": w[1],
  "THE TESTAMENT OF THE TWELVE PATRIARCHS": w[1],
  "THE TESTAMENT OF THE 12 PATRIARCHS": w[1],
  "TESTAMENT OF THE TWELVE PATRIARCHS": w[1],
  "TESTAMENT OF THE 12 PATRIARCHS": w[1],
  "TESTAMENTS OF THE 12 PATRIARCHS": w[1],
  "12 PATRIARCHS": w[1],
  "THE 12 PATRIARCHS": w[1],
  "THE TWELVE PATRIARCHS": w[1],
  "T 12 PATRIARCHS": w[1],
  "12 PATR": w[1],
  "DIDACHE": w[2],
  "THE DIDACHE": w[2],
  "THE BOOK OF MORMON": w[3],
  "BOFM": w[3],
  "BOM": w[3],
  "BOOK OF MORMON": w[3],
  "PEARL OF GREAT PRICE": w[4],
  "PGP": w[4],
  "THE PEARL OF GREAT PRICE": w[4],
  "PGOP": w[4],
  "DOCTRINE AND COVENANTS": w[5],
  "D&C": w[5],
  "D AND C": w[5],
  "THE DOCTRINE & COVENANTS": w[5],
  "DOCTRINE & COVENANTS": w[5],
  "THE DOCTRINE AND COVENANTS": w[5],
  "APOSTOLIC FATHERS": w[6],
  "FATHERS": w[6],
  "THE APOSTOLIC FATHERS": w[6],
};
export const books : BookShape[] = [
  {
    "workOsisID": "KJV",
    "bookName": "Genesis",
    "bookSubtitle": "The First Book of Moses called Genesis",
    "bookOsisID": "Gen",
    "paratext": "GEN",
    "groups": [
      "Old Testament",
      "Hebrew Bible",
      "Bible",
      "Pentatuech",
      "Torah"
    ],
    "aliases": [
      "Ge",
      "Gn",
      "The First Book of Moses called Genesis"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Moses"
    ],
    "traditions": [],
    "dateEarliest": "-1000-01-01",
    "dateLatest": "-0400-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Exodus",
    "bookSubtitle": "The Second Book of Moses, called Exodus",
    "bookOsisID": "Exod",
    "paratext": "EXO",
    "groups": [
      "Old Testament",
      "Hebrew Bible",
      "Bible",
      "Pentatuech",
      "Torah"
    ],
    "aliases": [
      "Ex",
      "The Second Book of Moses called Exodus"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Moses"
    ],
    "traditions": [],
    "dateEarliest": "-1000-01-01",
    "dateLatest": "-0400-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Leviticus",
    "bookSubtitle": "The Third Book of Moses, called Leviticus",
    "bookOsisID": "Lev",
    "paratext": "LEV",
    "groups": [
      "Old Testament",
      "Hebrew Bible",
      "Bible",
      "Pentatuech",
      "Torah"
    ],
    "aliases": [
      "Le",
      "The Third Book of Moses called Leviticus"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Moses"
    ],
    "traditions": [],
    "dateEarliest": "-0600-01-01",
    "dateLatest": "-0400-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Numbers",
    "bookSubtitle": "The Fourth Book of Moses, called Numbers",
    "bookOsisID": "Num",
    "paratext": "NUM",
    "groups": [
      "Old Testament",
      "Hebrew Bible",
      "Bible",
      "Pentatuech",
      "Torah"
    ],
    "aliases": [
      "Nu",
      "Nm",
      "Nb",
      "The Fourth Book of Moses called Numbers"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Moses"
    ],
    "traditions": [],
    "dateEarliest": "-0800-01-01",
    "dateLatest": "-0400-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Deuteronomy",
    "bookSubtitle": "The Fifth Book of Moses, called Deuteronomy",
    "bookOsisID": "Deut",
    "paratext": "DEU",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Deut",
      "Dt",
      "Du",
      "The Fifth Book of Moses called Deuteronomy"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Moses"
    ],
    "traditions": [],
    "dateEarliest": "-0620-01-01",
    "dateLatest": "-0500-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Joshua",
    "bookSubtitle": "The Book of Joshua",
    "bookOsisID": "Josh",
    "paratext": "JOS",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Josh"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Joshua"
    ],
    "traditions": [],
    "dateEarliest": "-0620-01-01",
    "dateLatest": "-0520-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Judges",
    "bookSubtitle": "The Book of Judges",
    "bookOsisID": "Judg",
    "paratext": "JDG",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Judg",
      "Jdg",
      "Jdgs",
      "Jg"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Samuel"
    ],
    "traditions": [],
    "dateEarliest": "-0620-01-01",
    "dateLatest": "-0520-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Ruth",
    "bookSubtitle": "The Book of Ruth",
    "bookOsisID": "Ruth",
    "paratext": "RUT",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Rth",
      "Ru"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Samuel"
    ],
    "traditions": [],
    "dateEarliest": "-0600-01-01",
    "dateLatest": "-0300-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "1 Samuel",
    "bookSubtitle": "The Book of 1 Samuel",
    "bookOsisID": "1Sam",
    "paratext": "1SA",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "1 Sam",
      "1 Sm",
      "1 Sa",
      "1 S",
      "I Sam",
      "I Sa",
      "1Sam",
      "1Sa",
      "1S",
      "1st Samuel",
      "1st Sam",
      "First Samuel",
      "First Sam"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Samuel",
      "Gad",
      "Nathan"
    ],
    "traditions": [],
    "dateEarliest": "-0620-01-01",
    "dateLatest": "-0520-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "2 Samuel",
    "bookSubtitle": "The Book of 2 Samuel",
    "bookOsisID": "2Sam",
    "paratext": "2SA",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "2 Sam",
      "2 Sm",
      "2 Sa",
      "2 S",
      "II Sam",
      "II Sa",
      "2Sam",
      "2Sa",
      "2S",
      "2nd Samuel",
      "2nd Sam",
      "Second Samuel",
      "Second Sam"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Gad",
      "Nathan"
    ],
    "traditions": [],
    "dateEarliest": "-0620-01-01",
    "dateLatest": "-0520-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "1 Kings",
    "bookSubtitle": "The First Book of Kings",
    "bookOsisID": "1Kgs",
    "paratext": "1KI",
    "groups": [
      "Old Testament",
      "Hebrew Bible",
      "Bible",
      "Kings"
    ],
    "aliases": [
      "1 Kgs",
      "1 Ki",
      "1Kin",
      "1K",
      "I Kgs",
      "I Ki",
      "1st Kings",
      "1st Kgs",
      "First Kings",
      "First Kgs"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Jeremiah"
    ],
    "traditions": [],
    "dateEarliest": "-0620-01-01",
    "dateLatest": "-0520-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "2 Kings",
    "bookSubtitle": "The Second Book of Kings",
    "bookOsisID": "2Kgs",
    "paratext": "2KI",
    "groups": [
      "Old Testament",
      "Hebrew Bible",
      "Bible",
      "Kings"
    ],
    "aliases": [
      "2 Kgs",
      "2 Ki",
      "2Kin",
      "2K",
      "II Kgs",
      "II Ki",
      "2nd Kings",
      "2nd Kgs",
      "Second Kings",
      "Second Kgs"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Jeremiah"
    ],
    "traditions": [],
    "dateEarliest": "-0620-01-01",
    "dateLatest": "-0520-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "1 Chronicles",
    "bookSubtitle": "The First Book of Chronicles",
    "bookOsisID": "1Chr",
    "paratext": "1CH",
    "groups": [
      "Old Testament",
      "Hebrew Bible",
      "Bible",
      "Persian Period"
    ],
    "aliases": [
      "1 Chron",
      "1 Chr",
      "1 Ch",
      "1Chron",
      "1Chr",
      "1Ch",
      "I Chron",
      "I Chr",
      "I Ch",
      "1st Chronicles",
      "1st Chron",
      "First Chronicles",
      "First Chron"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Ezra"
    ],
    "traditions": [],
    "dateEarliest": "-0400-01-01",
    "dateLatest": "-0300-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "2 Chronicles",
    "bookSubtitle": "The Second Book of Chronicals",
    "bookOsisID": "2Chr",
    "paratext": "2CH",
    "groups": [
      "Old Testament",
      "Hebrew Bible",
      "Bible",
      "Persian Period"
    ],
    "aliases": [
      "2 Chron",
      "2 Chr",
      "2 Ch",
      "2Chron",
      "2Chr",
      "2Ch",
      "II Chron",
      "II Chr",
      "II Ch",
      "2nd Chronicles",
      "2nd Chron",
      "Second Chronicles",
      "Second Chron"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Ezra"
    ],
    "traditions": [],
    "dateEarliest": "-0400-01-01",
    "dateLatest": "-0300-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Ezra",
    "bookSubtitle": "The Book of Ezra",
    "bookOsisID": "Ezra",
    "paratext": "EZR",
    "groups": [
      "Old Testament",
      "Hebrew Bible",
      "Bible",
      "Persian Period"
    ],
    "aliases": [
      "Ez"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Ezra"
    ],
    "traditions": [],
    "dateEarliest": "-0450-01-01",
    "dateLatest": "-0390-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Nehemiah",
    "bookSubtitle": "The Book of Nehemiah",
    "bookOsisID": "Neh",
    "paratext": "NEH",
    "groups": [
      "Old Testament",
      "Hebrew Bible",
      "Bible",
      "Persian Period"
    ],
    "aliases": [
      "Ne"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Nehemiah",
      "Ezra"
    ],
    "traditions": [],
    "dateEarliest": "-0445-01-01",
    "dateLatest": "-0390-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Esther",
    "bookSubtitle": "The Book of Esther",
    "bookOsisID": "Esth",
    "paratext": "EST",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Es"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Mordecai"
    ],
    "traditions": [],
    "dateEarliest": "-0400-01-01",
    "dateLatest": "-0250-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Job",
    "bookSubtitle": "The Book of Job",
    "bookOsisID": "Job",
    "paratext": "JOB",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Jb"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Job",
      "Moses"
    ],
    "traditions": [],
    "dateEarliest": "-0700-01-01",
    "dateLatest": "-0300-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Psalms",
    "bookSubtitle": "The Book of Psalms",
    "bookOsisID": "Ps",
    "paratext": "PSA",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Psalm",
      "Pslm",
      "Psm",
      "Pss"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "David",
      "Asaph",
      "Sons of Korah",
      "Solomon",
      "Moses",
      "Ethan",
      "Heman"
    ],
    "traditions": [],
    "dateEarliest": "-1000-01-01",
    "dateLatest": "-0100-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Proverbs",
    "bookSubtitle": "The Book of Proverbs",
    "bookOsisID": "Prov",
    "paratext": "PRO",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Prv",
      "Pv"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Solomon",
      "Agur",
      "Lemuel"
    ],
    "traditions": [],
    "dateEarliest": "-0900-01-01",
    "dateLatest": "-0300-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Ecclesiastes",
    "bookSubtitle": "The Book of Ecclesiastes",
    "bookOsisID": "Eccl",
    "paratext": "ECC",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Qohelet"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Solomon"
    ],
    "traditions": [],
    "dateEarliest": "-0300-01-01",
    "dateLatest": "-0200-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Song of Solomon",
    "bookSubtitle": "The Book of Song of Solomon",
    "bookOsisID": "Song",
    "paratext": "SNG",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Canticle of Canticles",
      "Song",
      "SNG",
      "Solomon's Song"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Solomon"
    ],
    "traditions": [],
    "dateEarliest": "-0700-01-01",
    "dateLatest": "-0200-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Isaiah",
    "bookSubtitle": "The Book of Isaiah",
    "bookOsisID": "Isa",
    "paratext": "ISA",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Is"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Isaiah"
    ],
    "traditions": [],
    "dateEarliest": "-0740-01-01",
    "dateLatest": "-0400-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Jeremiah",
    "bookSubtitle": "The Book of Jeremiah",
    "bookOsisID": "Jer",
    "paratext": "JER",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Je",
      "Jr"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Jeremiah"
    ],
    "traditions": [],
    "dateEarliest": "-0627-01-01",
    "dateLatest": "-0550-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Lamentations",
    "bookSubtitle": "The Book of Lamentations",
    "bookOsisID": "Lam",
    "paratext": "LAM",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "La"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Jeremiah"
    ],
    "traditions": [],
    "dateEarliest": "-0586-01-01",
    "dateLatest": "-0520-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Ezekiel",
    "bookSubtitle": "The Book of Ezekiel",
    "bookOsisID": "Ezek",
    "paratext": "EZK",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Ezk"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Ezekiel"
    ],
    "traditions": [],
    "dateEarliest": "-0593-01-01",
    "dateLatest": "-0530-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Daniel",
    "bookSubtitle": "The Book of Daniel",
    "bookOsisID": "Dan",
    "paratext": "DAN",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Da",
      "Dn"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Daniel"
    ],
    "traditions": [],
    "dateEarliest": "-0200-01-01",
    "dateLatest": "-0164-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Hosea",
    "bookSubtitle": "The Book of Hosea",
    "bookOsisID": "Hos",
    "paratext": "HOS",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Ho"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Hosea"
    ],
    "traditions": [],
    "dateEarliest": "-0750-01-01",
    "dateLatest": "-0500-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Joel",
    "bookSubtitle": "The Book of Joel",
    "bookOsisID": "Joel",
    "paratext": "JOL",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Jl"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Joel"
    ],
    "traditions": [],
    "dateEarliest": "-0500-01-01",
    "dateLatest": "-0300-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Amos",
    "bookSubtitle": "The Book of Amos",
    "bookOsisID": "Amos",
    "paratext": "AMO",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Am"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Amos"
    ],
    "traditions": [],
    "dateEarliest": "-0760-01-01",
    "dateLatest": "-0500-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Obadiah",
    "bookSubtitle": "The Book of Obadiah",
    "bookOsisID": "Obad",
    "paratext": "OBA",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Ob"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Obadiah"
    ],
    "traditions": [],
    "dateEarliest": "-0586-01-01",
    "dateLatest": "-0450-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Jonah",
    "bookSubtitle": "The Book of Jonah",
    "bookOsisID": "Jonah",
    "paratext": "JON",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Jonah"
    ],
    "traditions": [],
    "dateEarliest": "-0400-01-01",
    "dateLatest": "-0250-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Micah",
    "bookSubtitle": "The Book of Micah",
    "bookOsisID": "Mic",
    "paratext": "MIC",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Mc"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Micah"
    ],
    "traditions": [],
    "dateEarliest": "-0737-01-01",
    "dateLatest": "-0500-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Nahum",
    "bookSubtitle": "The Book of Nahum",
    "bookOsisID": "Nah",
    "paratext": "NAM",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Nh",
      "Nhm"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Nahum"
    ],
    "traditions": [],
    "dateEarliest": "-0650-01-01",
    "dateLatest": "-0612-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Habakkuk",
    "bookSubtitle": "The Book of Habakkuk",
    "bookOsisID": "Hab",
    "paratext": "HAB",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Hb"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Habakkuk"
    ],
    "traditions": [],
    "dateEarliest": "-0625-01-01",
    "dateLatest": "-0587-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Zephaniah",
    "bookSubtitle": "The Book of Zephaniah",
    "bookOsisID": "Zeph",
    "paratext": "ZEP",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Zp"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Zephaniah"
    ],
    "traditions": [],
    "dateEarliest": "-0630-01-01",
    "dateLatest": "-0625-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Haggai",
    "bookSubtitle": "The Book of Haggai",
    "bookOsisID": "Hag",
    "paratext": "HAG",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Hg",
      "Hgi",
      "Hagi"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Haggai"
    ],
    "traditions": [],
    "dateEarliest": "-0520-01-01",
    "dateLatest": "-0519-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Zechariah",
    "bookSubtitle": "The Book of Zechariah",
    "bookOsisID": "Zech",
    "paratext": "ZEC",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Zc"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Zechariah"
    ],
    "traditions": [],
    "dateEarliest": "-0520-01-01",
    "dateLatest": "-0440-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Malachi",
    "bookSubtitle": "The Book of Malachi",
    "bookOsisID": "Mal",
    "paratext": "MAL",
    "groups": [
      "Hebrew Bible",
      "Old Testament",
      "Bible"
    ],
    "aliases": [
      "Ml"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Malachi"
    ],
    "traditions": [],
    "dateEarliest": "-0450-01-01",
    "dateLatest": "-0400-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Matthew",
    "bookSubtitle": "The Gospel According to St. Matthew",
    "bookOsisID": "Matt",
    "paratext": "MAT",
    "groups": [
      "New Testament",
      "Bible",
      "Gospels"
    ],
    "aliases": [
      "St Matthew",
      "St. Matthew",
      "Saint Matthew",
      "The Gospel According to St Matthew",
      "The Gospel According to St. Matthew",
      "The Gospel According to Saint Matthew"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "St. Matthew"
    ],
    "traditions": [],
    "dateEarliest": "0070-01-01",
    "dateLatest": "0100-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Mark",
    "bookSubtitle": "The Gospel According to St. Mark",
    "bookOsisID": "Mark",
    "paratext": "MRK",
    "groups": [
      "New Testament",
      "Bible",
      "Gospels"
    ],
    "aliases": [
      "St Mark",
      "St. Mark",
      "Saint Mark",
      "The Gospel According to St Mark",
      "The Gospel According to St. Mark",
      "The Gospel According to Saint Mark"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "St. Mark"
    ],
    "traditions": [],
    "dateEarliest": "0065-01-01",
    "dateLatest": "0075-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Luke",
    "bookSubtitle": "The Gospel According to St. Luke",
    "bookOsisID": "Luke",
    "paratext": "LUK",
    "groups": [
      "New Testament",
      "Bible",
      "Gospels"
    ],
    "aliases": [
      "St Luke",
      "St. Luke",
      "Saint Luke",
      "The Gospel According to St Luke",
      "The Gospel According to St. Luke",
      "The Gospel According to Saint Luke"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "St. Luke"
    ],
    "traditions": [],
    "dateEarliest": "0080-01-01",
    "dateLatest": "0110-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "John",
    "bookSubtitle": "The Gospel According to St. John",
    "bookOsisID": "John",
    "paratext": "JHN",
    "groups": [
      "New Testament",
      "Bible",
      "Gospels"
    ],
    "aliases": [
      "St John",
      "St. John",
      "Saint John",
      "The Gospel According to St John",
      "The Gospel According to St. John",
      "The Gospel According to Saint John"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "St. John"
    ],
    "traditions": [],
    "dateEarliest": "0090-01-01",
    "dateLatest": "0110-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Acts",
    "bookSubtitle": "The Acts of the Apostles",
    "bookOsisID": "Acts",
    "paratext": "ACT",
    "groups": [
      "New Testament",
      "Bible"
    ],
    "aliases": [
      "Ac"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Luke"
    ],
    "traditions": [],
    "dateEarliest": "0080-01-01",
    "dateLatest": "0110-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Romans",
    "bookSubtitle": "The Epistle of Paul to the Romans ",
    "bookOsisID": "Rom",
    "paratext": "ROM",
    "groups": [
      "New Testament",
      "Bible",
      "Pauline Epistles"
    ],
    "aliases": [
      "Ro",
      "Rm"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Paul"
    ],
    "traditions": [],
    "dateEarliest": "0056-01-01",
    "dateLatest": "0058-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "1 Corinthians",
    "bookSubtitle": "The First Epistle of Paul to the Corinthians ",
    "bookOsisID": "1Cor",
    "paratext": "1CO",
    "groups": [
      "New Testament",
      "Bible",
      "Pauline Epistles"
    ],
    "aliases": [
      "1 Cor",
      "1 Co",
      "I Cor",
      "I Co",
      "1Cor",
      "1Co",
      "I Corinthians",
      "1Corinthians",
      "1st Corinthians",
      "First Corinthians"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Paul"
    ],
    "traditions": [],
    "dateEarliest": "0053-01-01",
    "dateLatest": "0055-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "2 Corinthians",
    "bookSubtitle": "The Second Epistle of Paul to the Corinthians ",
    "bookOsisID": "2Cor",
    "paratext": "2CO",
    "groups": [
      "New Testament",
      "Bible",
      "Pauline Epistles"
    ],
    "aliases": [
      "2 Cor",
      "2 Co",
      "II Cor",
      "II Co",
      "2Cor",
      "2Co",
      "II Corinthians",
      "2Corinthians",
      "2nd Corinthians",
      "Second Corinthians"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Paul"
    ],
    "traditions": [],
    "dateEarliest": "0055-01-01",
    "dateLatest": "0057-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Galatians",
    "bookSubtitle": "The Epistle of Paul to the Galatians ",
    "bookOsisID": "Gal",
    "paratext": "GAL",
    "groups": [
      "New Testament",
      "Bible",
      "Pauline Epistles"
    ],
    "aliases": [
      "Ga"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Paul"
    ],
    "traditions": [],
    "dateEarliest": "0048-01-01",
    "dateLatest": "0055-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Ephesians",
    "bookSubtitle": "The Epistle of Paul to the Ephesians ",
    "bookOsisID": "Eph",
    "paratext": "EPH",
    "groups": [
      "New Testament",
      "Bible",
      "Pauline Epistles"
    ],
    "aliases": [
      "Ephes",
      "Ep"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Paul"
    ],
    "traditions": [],
    "dateEarliest": "0060-01-01",
    "dateLatest": "0100-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Philippians",
    "bookSubtitle": "The Epistle of Paul to the Philippians ",
    "bookOsisID": "Phil",
    "paratext": "PHP",
    "groups": [
      "New Testament",
      "Bible",
      "Pauline Epistles"
    ],
    "aliases": [
      "Pp"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Paul"
    ],
    "traditions": [],
    "dateEarliest": "0054-01-01",
    "dateLatest": "0062-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Colossians",
    "bookSubtitle": "The Epistle of Paul to the Colossians ",
    "bookOsisID": "Col",
    "paratext": "COL",
    "groups": [
      "New Testament",
      "Bible",
      "Pauline Epistles"
    ],
    "aliases": [
      "Co"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Paul"
    ],
    "traditions": [],
    "dateEarliest": "0060-01-01",
    "dateLatest": "0090-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "1 Thessalonians",
    "bookSubtitle": "The First Epistle of Paul to the Thessalonians ",
    "bookOsisID": "1Thess",
    "paratext": "1TH",
    "groups": [
      "New Testament",
      "Bible",
      "Pauline Epistles"
    ],
    "aliases": [
      "1 Thess",
      "1 Thes",
      "1 Th",
      "I Thessalonians",
      "I Thess",
      "I Thes",
      "I Th",
      "1Thessalonians",
      "1Thess",
      "1Thes",
      "1Th",
      "1st Thessalonians",
      "1st Thess",
      "First Thessalonians",
      "First Thess"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Paul"
    ],
    "traditions": [],
    "dateEarliest": "0049-01-01",
    "dateLatest": "0051-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "2 Thessalonians",
    "bookSubtitle": "The Second Epistle of Paul to the Thessalonians ",
    "bookOsisID": "2Thess",
    "paratext": "2TH",
    "groups": [
      "New Testament",
      "Bible",
      "Pauline Epistles"
    ],
    "aliases": [
      "2 Thess",
      "2 Thes",
      "2 Th",
      "II Thessalonians",
      "II Thess",
      "II Thes",
      "II Th",
      "2Thessalonians",
      "2Thess",
      "2Thes",
      "2Th",
      "2nd Thessalonians",
      "2nd Thess",
      "Second Thessalonians",
      "Second Thess"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Paul"
    ],
    "traditions": [],
    "dateEarliest": "0050-01-01",
    "dateLatest": "0100-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "1 Timothy",
    "bookSubtitle": "The First Epistle of Paul to Timothy ",
    "bookOsisID": "1Tim",
    "paratext": "1TI",
    "groups": [
      "New Testament",
      "Bible",
      "Pauline Epistles"
    ],
    "aliases": [
      "1 Tim",
      "1 Ti",
      "I Timothy",
      "I Tim",
      "I Ti",
      "1Timothy",
      "1Tim",
      "1Ti",
      "1st Timothy",
      "1st Tim",
      "First Timothy",
      "First Tim"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Paul"
    ],
    "traditions": [],
    "dateEarliest": "0065-01-01",
    "dateLatest": "0110-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "2 Timothy",
    "bookSubtitle": "The Second Epistle of Paul to Timothy ",
    "bookOsisID": "2Tim",
    "paratext": "2TI",
    "groups": [
      "New Testament",
      "Bible",
      "Pauline Epistles"
    ],
    "aliases": [
      "2 Tim",
      "2 Ti",
      "II Timothy",
      "II Tim",
      "II Ti",
      "2Timothy",
      "2Tim",
      "2Ti",
      "2nd Timothy",
      "2nd Tim",
      "Second Timothy",
      "Second Tim"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Paul"
    ],
    "traditions": [],
    "dateEarliest": "0065-01-01",
    "dateLatest": "0110-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Titus",
    "bookSubtitle": "The Epistle of Paul to Titus ",
    "bookOsisID": "Titus",
    "paratext": "TIT",
    "groups": [
      "New Testament",
      "Bible",
      "Pauline Epistles"
    ],
    "aliases": [
      "Ti",
      "Tts"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Paul"
    ],
    "traditions": [],
    "dateEarliest": "0065-01-01",
    "dateLatest": "0110-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Philemon",
    "bookSubtitle": "The Epistle of Paul to Philemon ",
    "bookOsisID": "Phlm",
    "paratext": "PHM",
    "groups": [
      "New Testament",
      "Bible",
      "Pauline Epistles"
    ],
    "aliases": [
      "Pm"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Paul"
    ],
    "traditions": [],
    "dateEarliest": "0054-01-01",
    "dateLatest": "0062-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Hebrews",
    "bookSubtitle": "The Epistle to the Hebrews ",
    "bookOsisID": "Heb",
    "paratext": "HEB",
    "groups": [
      "New Testament",
      "Bible"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [],
    "traditions": [],
    "dateEarliest": "0060-01-01",
    "dateLatest": "0095-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "James",
    "bookSubtitle": "The General Epistle of James ",
    "bookOsisID": "Jas",
    "paratext": "JAS",
    "groups": [
      "New Testament",
      "Bible"
    ],
    "aliases": [
      "Jm"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "James the brother of Jesus"
    ],
    "traditions": [],
    "dateEarliest": "0048-01-01",
    "dateLatest": "0110-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "1 Peter",
    "bookSubtitle": "The First Epistle of Peter ",
    "bookOsisID": "1Pet",
    "paratext": "1PE",
    "groups": [
      "New Testament",
      "Bible"
    ],
    "aliases": [
      "1 Pet",
      "1 Pe",
      "1 Pt",
      "1 P",
      "I Pet",
      "I Pt",
      "I Pe",
      "1Peter",
      "1Pet",
      "1Pe",
      "1Pt",
      "1P",
      "I Peter",
      "1st Peter",
      "First Peter"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Peter"
    ],
    "traditions": [],
    "dateEarliest": "0060-01-01",
    "dateLatest": "0090-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "2 Peter",
    "bookSubtitle": "The Second Epistle of Peter ",
    "bookOsisID": "2Pet",
    "paratext": "2PE",
    "groups": [
      "New Testament",
      "Bible"
    ],
    "aliases": [
      "2 Pet",
      "2 Pe",
      "2 Pt",
      "2 P",
      "II Peter",
      "II Pet",
      "II Pt",
      "II Pe",
      "2Peter",
      "2Pet",
      "2Pe",
      "2Pt",
      "2P",
      "2nd Peter",
      "Second Peter"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Peter"
    ],
    "traditions": [],
    "dateEarliest": "0080-01-01",
    "dateLatest": "0150-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "1 John",
    "bookSubtitle": "The First Epistle of John ",
    "bookOsisID": "1John",
    "paratext": "1JN",
    "groups": [
      "New Testament",
      "Bible"
    ],
    "aliases": [
      "1 John",
      "1 Jhn",
      "1 Jn",
      "1 J",
      "1John",
      "1Jhn",
      "1Joh",
      "1Jn",
      "1Jo",
      "1J",
      "I John",
      "I Jhn",
      "I Joh",
      "I Jn",
      "I Jo",
      "1st John",
      "First John"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "The Apostle John"
    ],
    "traditions": [],
    "dateEarliest": "0090-01-01",
    "dateLatest": "0110-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "2 John",
    "bookSubtitle": "The Second Epistle of John ",
    "bookOsisID": "2John",
    "paratext": "2JN",
    "groups": [
      "New Testament",
      "Bible"
    ],
    "aliases": [
      "2 John",
      "2 Jhn",
      "2 Jn",
      "2 J",
      "2John",
      "2Jhn",
      "2Joh",
      "2Jn",
      "2Jo",
      "2J",
      "II John",
      "II Jhn",
      "II Joh",
      "II Jn",
      "II Jo",
      "2nd John",
      "Second John"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "The Apostle John"
    ],
    "traditions": [],
    "dateEarliest": "0090-01-01",
    "dateLatest": "0110-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "3 John",
    "bookSubtitle": "The Third Epistle of John ",
    "bookOsisID": "3John",
    "paratext": "3JN",
    "groups": [
      "New Testament",
      "Bible"
    ],
    "aliases": [
      "3 John",
      "3 Jhn",
      "3 Jn",
      "3 J",
      "3John",
      "3Jhn",
      "3Joh",
      "3Jn",
      "3Jo",
      "3J",
      "III John",
      "III Jhn",
      "III Joh",
      "III Jn",
      "III Jo",
      "3rd John",
      "Third John"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "The Apostle John"
    ],
    "traditions": [],
    "dateEarliest": "0090-01-01",
    "dateLatest": "0110-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Jude",
    "bookSubtitle": "The Epistle of Jude ",
    "bookOsisID": "Jude",
    "paratext": "JUD",
    "groups": [
      "New Testament",
      "Bible"
    ],
    "aliases": [
      "Jd"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Jude"
    ],
    "traditions": [],
    "dateEarliest": "0060-01-01",
    "dateLatest": "0110-12-31"
  },
  {
    "workOsisID": "KJV",
    "bookName": "Revelation",
    "bookSubtitle": "The Revelation of Jesus Christ (or The Apocalypse of John) ",
    "bookOsisID": "Rev",
    "paratext": "REV",
    "groups": [
      "New Testament",
      "Bible"
    ],
    "aliases": [
      "Re",
      "The Revelation"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "John the Revelator"
    ],
    "traditions": [],
    "dateEarliest": "0068-01-01",
    "dateLatest": "0096-12-31"
  },
  {
    "workOsisID": "KJVA",
    "bookName": "Tobit",
    "bookSubtitle": "The Book of Tobit",
    "bookOsisID": "Tob",
    "paratext": "TOB",
    "groups": [
      "Deuterocannon",
      "Apocrypha"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Tobit"
    ],
    "traditions": [],
    "dateEarliest": "-0225-01-01",
    "dateLatest": "-0175-12-31"
  },
  {
    "workOsisID": "KJVA",
    "bookName": "Judith",
    "bookSubtitle": "The Book of Judith",
    "bookOsisID": "Jdt",
    "paratext": "JDT",
    "groups": [
      "Deuterocannon",
      "Apocrypha"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Judith"
    ],
    "traditions": [],
    "dateEarliest": "-0150-01-01",
    "dateLatest": "-0100-12-31"
  },
  {
    "workOsisID": "KJVA",
    "bookName": "Additions to Esther",
    "bookSubtitle": "The Rest of the Chapters of the Book of Esther, which are found neither in the Hebrew, nor in the Chaldee",
    "bookOsisID": "AddEsth",
    "paratext": "ADE",
    "groups": [
      "Deuterocannon",
      "Apocrypha"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Mordecai",
      "Esther"
    ],
    "traditions": [],
    "dateEarliest": "-0116-01-01",
    "dateLatest": "-0048-12-31"
  },
  {
    "workOsisID": "KJVA",
    "bookName": "Wisdom",
    "bookSubtitle": "The Wisdom of Solomon",
    "bookOsisID": "Wis",
    "paratext": "WIS",
    "groups": [
      "Deuterocannon",
      "Apocrypha"
    ],
    "aliases": [
      "Wisdom of Solomon"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Solomon"
    ],
    "traditions": [],
    "dateEarliest": "-0100-01-01",
    "dateLatest": "0010-12-31"
  },
  {
    "workOsisID": "KJVA",
    "bookName": "Sirach Prologue",
    "bookSubtitle": "The Wisdom of Jesus the Son of Sirach (Prologue)",
    "bookOsisID": "SirP",
    "paratext": null,
    "groups": [
      "Deuterocannon",
      "Apocrypha"
    ],
    "aliases": [
      "Ecclesiasticus Prologue"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [],
    "traditions": [],
    "dateEarliest": "-0175-01-01",
    "dateLatest": "-0132-12-31"
  },
  {
    "workOsisID": "KJVA",
    "bookName": "Sirach",
    "bookSubtitle": "The Wisdom of Jesus the Son of Sirach",
    "bookOsisID": "Sir",
    "paratext": "SIR",
    "groups": [
      "Deuterocannon",
      "Apocrypha"
    ],
    "aliases": [
      "Ecclesiasticus"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Jesus son of Sirach"
    ],
    "traditions": [],
    "dateEarliest": "-0196-01-01",
    "dateLatest": "-0175-12-31"
  },
  {
    "workOsisID": "KJVA",
    "bookName": "Prayer of Azariah",
    "bookSubtitle": "Song of the Three Holy Children",
    "bookOsisID": "PrAzar",
    "paratext": "S3Y",
    "groups": [
      "Deuterocannon",
      "Apocrypha"
    ],
    "aliases": [
      "Song of the Three Children",
      "Song of the Three Holy Children",
      "PrAzar",
      "S3Y"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Azariah"
    ],
    "traditions": [],
    "dateEarliest": "-0160-01-01",
    "dateLatest": "-0140-12-31"
  },
  {
    "workOsisID": "KJVA",
    "bookName": "Susanna",
    "bookSubtitle": "History of Susanna",
    "bookOsisID": "Sus",
    "paratext": "SUS",
    "groups": [
      "Deuterocannon",
      "Apocrypha"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Daniel"
    ],
    "traditions": [],
    "dateEarliest": "-0100-01-01",
    "dateLatest": "-0050-12-31"
  },
  {
    "workOsisID": "KJVA",
    "bookName": "1 Maccabees",
    "bookSubtitle": "The First Book of the Maccabees",
    "bookOsisID": "1Macc",
    "paratext": "1MA",
    "groups": [
      "Deuterocannon",
      "Apocrypha"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [],
    "traditions": [],
    "dateEarliest": "-0100-01-01",
    "dateLatest": "-0090-12-31"
  },
  {
    "workOsisID": "KJVA",
    "bookName": "2 Maccabees",
    "bookSubtitle": "The Second Book of the Maccabees",
    "bookOsisID": "2Macc",
    "paratext": "2MA",
    "groups": [
      "Deuterocannon",
      "Apocrypha"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [],
    "traditions": [],
    "dateEarliest": "-0124-01-01",
    "dateLatest": "-0120-12-31"
  },
  {
    "workOsisID": "KJVA",
    "bookName": "Prayer of Manasseh",
    "bookSubtitle": "The Prayer of Manasses King of Juda, when he was holden captive in Babylon",
    "bookOsisID": "PrMan",
    "paratext": "MAN",
    "groups": [
      "Deuterocannon",
      "Apocrypha"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Manasseh"
    ],
    "traditions": [],
    "dateEarliest": "-0200-01-01",
    "dateLatest": "0000-12-31"
  },
  {
    "workOsisID": "KJVA",
    "bookName": "1 Esdras",
    "bookSubtitle": "The First Book of Esdras",
    "bookOsisID": "1Esd",
    "paratext": "1ES",
    "groups": [
      "Deuterocannon",
      "Apocrypha"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Ezra"
    ],
    "traditions": [],
    "dateEarliest": "-0200-01-01",
    "dateLatest": "-0100-12-31"
  },
  {
    "workOsisID": "KJVA",
    "bookName": "2 Esdras",
    "bookSubtitle": "The Second Book of Esdras",
    "bookOsisID": "2Esd",
    "paratext": "2ES",
    "groups": [
      "Deuterocannon",
      "Apocrypha"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Ezra"
    ],
    "traditions": [],
    "dateEarliest": "0070-01-01",
    "dateLatest": "0120-12-31"
  },
  {
    "workOsisID": "Vulgate",
    "bookName": "Epistle to the Laodiceans",
    "bookSubtitle": "Epistle to the Laodiceans",
    "bookOsisID": "EpLao",
    "paratext": "LAO",
    "groups": [
      "Vulgate",
      "Apocrypha"
    ],
    "aliases": [
      "EpLao",
      "LAO",
      "Laodiceans"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Paul"
    ],
    "traditions": [],
    "dateEarliest": "0080-01-01",
    "dateLatest": "0140-12-31"
  },
  {
    "workOsisID": "Fathers",
    "bookName": "Didache",
    "bookSubtitle": "The Lord's Teaching Through the Twelve Apostles to the Nations",
    "bookOsisID": "Did",
    "paratext": "DID",
    "groups": [
      "Apostolic Fathers",
      "Apocrypha"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [],
    "traditions": [],
    "dateEarliest": "0080-01-01",
    "dateLatest": "0100-12-31"
  },
  {
    "workOsisID": "BofM",
    "bookName": "1 Nephi",
    "bookSubtitle": "",
    "bookOsisID": "1Ne",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "Small Plates of Nephi",
      "LDS"
    ],
    "aliases": [
      "1 Ne",
      "1st Nephi",
      "First Nephi",
      "The First Book of Nephi",
      "I Nephi"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Nephi"
    ],
    "traditions": [],
    "dateEarliest": "-0600-01-01",
    "dateLatest": "-0570-01-01"
  },
  {
    "workOsisID": "BofM",
    "bookName": "2 Nephi",
    "bookSubtitle": "",
    "bookOsisID": "2Ne",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "Small Plates of Nephi",
      "LDS"
    ],
    "aliases": [
      "2 Ne",
      "2nd Nephi",
      "Second Nephi",
      "The Second Book of Nephi",
      "II Nephi"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Nephi"
    ],
    "traditions": [],
    "dateEarliest": "-0588-01-01",
    "dateLatest": "-0545-01-01"
  },
  {
    "workOsisID": "BofM",
    "bookName": "Jacob",
    "bookSubtitle": "the Brother of Nephi",
    "bookOsisID": "Jac",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "Small Plates of Nephi",
      "LDS"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Jacob"
    ],
    "traditions": [],
    "dateEarliest": "-0544-01-01",
    "dateLatest": "-0421-01-01"
  },
  {
    "workOsisID": "BofM",
    "bookName": "Enos",
    "bookSubtitle": "",
    "bookOsisID": "Enos",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "Small Plates of Nephi",
      "LDS"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Enos"
    ],
    "traditions": [],
    "dateEarliest": "-0420-01-01",
    "dateLatest": "-0420-01-01"
  },
  {
    "workOsisID": "BofM",
    "bookName": "Jarom",
    "bookSubtitle": "",
    "bookOsisID": "Jar",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "Small Plates of Nephi",
      "LDS"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Jarom"
    ],
    "traditions": [],
    "dateEarliest": "-0399-01-01",
    "dateLatest": "-0361-01-01"
  },
  {
    "workOsisID": "BofM",
    "bookName": "Omni",
    "bookSubtitle": "",
    "bookOsisID": "Omni",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "Small Plates of Nephi",
      "LDS"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Omni",
      "Chemish",
      "Abinadom",
      "Amaleki"
    ],
    "traditions": [],
    "dateEarliest": "-0323-01-01",
    "dateLatest": "-0130-01-01"
  },
  {
    "workOsisID": "BofM",
    "bookName": "Words of Mormon",
    "bookSubtitle": "",
    "bookOsisID": "WoM",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "LDS",
      "Mormon"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Mormon"
    ],
    "traditions": [],
    "dateEarliest": "0385-01-01",
    "dateLatest": "0385-01-01"
  },
  {
    "workOsisID": "BofM",
    "bookName": "Mosiah",
    "bookSubtitle": "",
    "bookOsisID": "Mosi",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "LDS",
      "Mormon",
      "Large Plates of Nephi",
      "Abridgement"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Mormon"
    ],
    "traditions": [],
    "dateEarliest": "-0130-01-01",
    "dateLatest": "-0091-01-01"
  },
  {
    "workOsisID": "BofM",
    "bookName": "Alma",
    "bookSubtitle": "the Son of Alma",
    "bookOsisID": "Alma",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "LDS",
      "Mormon",
      "Large Plates of Nephi",
      "Abridgement"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Mormon"
    ],
    "traditions": [],
    "dateEarliest": "-0091-01-01",
    "dateLatest": "-0052-01-01"
  },
  {
    "workOsisID": "BofM",
    "bookName": "Helaman",
    "bookSubtitle": "",
    "bookOsisID": "Hel",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "LDS",
      "Mormon",
      "Large Plates of Nephi",
      "Abridgement"
    ],
    "aliases": [
      "He",
      "Hlm",
      "Helm"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Mormon"
    ],
    "traditions": [],
    "dateEarliest": "-0052-01-01",
    "dateLatest": "-0001-01-01"
  },
  {
    "workOsisID": "BofM",
    "bookName": "3 Nephi",
    "bookSubtitle": "the Son of Nephi, Who Was the Son of Helaman",
    "bookOsisID": "3Ne",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "LDS",
      "Mormon",
      "Large Plates of Nephi",
      "Abridgement"
    ],
    "aliases": [
      "3 Ne",
      "3rd Nephi",
      "Third Nephi",
      "III Nephi"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Mormon"
    ],
    "traditions": [],
    "dateEarliest": "0005-01-01",
    "dateLatest": "0035-01-01"
  },
  {
    "workOsisID": "BofM",
    "bookName": "4 Nephi",
    "bookSubtitle": "Who Is the Son of Nephi—One of the Disciples of Jesus Christ",
    "bookOsisID": "4Ne",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "LDS",
      "Mormon",
      "Large Plates of Nephi",
      "Abridgement"
    ],
    "aliases": [
      "4 Ne",
      "4th Nephi",
      "Fourth Nephi",
      "IV Nephi"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Mormon"
    ],
    "traditions": [],
    "dateEarliest": "0035-01-01",
    "dateLatest": "0321-01-01"
  },
  {
    "workOsisID": "BofM",
    "bookName": "Mormon",
    "bookSubtitle": "",
    "bookOsisID": "Morm",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "LDS",
      "Mormon",
      "Large Plates of Nephi",
      "Abridgement"
    ],
    "aliases": [
      "Mmn"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Mormon"
    ],
    "traditions": [],
    "dateEarliest": "0321-01-01",
    "dateLatest": "0421-01-01"
  },
  {
    "workOsisID": "BofM",
    "bookName": "Ether",
    "bookSubtitle": "The record of the Jaredites, taken from the twenty-four plates found by the people of Limhi in the days of King Mosiah.",
    "bookOsisID": "Eth",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "LDS",
      "Mormon",
      "Large Plates of Nephi",
      "Abridgement"
    ],
    "aliases": [],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Mormon"
    ],
    "traditions": [],
    "dateEarliest": "-2200-01-01",
    "dateLatest": "-0350-01-01"
  },
  {
    "workOsisID": "BofM",
    "bookName": "Moroni",
    "bookSubtitle": "",
    "bookOsisID": "Moro",
    "paratext": null,
    "groups": [
      "Book of Mormon",
      "LDS",
      "Mormon",
      "Large Plates of Nephi",
      "Abridgement"
    ],
    "aliases": [
      "Mni"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Mormon"
    ],
    "traditions": [],
    "dateEarliest": "0401-01-01",
    "dateLatest": "0401-01-01"
  },
  {
    "workOsisID": "PGP",
    "bookName": "Moses",
    "bookSubtitle": "Selections from the Book of Moses",
    "bookOsisID": "Mos",
    "paratext": null,
    "groups": [
      "Pearl of Great Price",
      "Inspired Translation",
      "Joseph Smith Translation",
      "JST",
      "Joseph Smith",
      "LDS"
    ],
    "aliases": [
      "The Book of Moses"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Moses"
    ],
    "traditions": [],
    "dateEarliest": "06-01-1830",
    "dateLatest": "02-01-1831"
  },
  {
    "workOsisID": "PGP",
    "bookName": "Abraham",
    "bookSubtitle": "Translated from the Papyrus, by Joseph Smith",
    "bookOsisID": "Abr",
    "paratext": null,
    "groups": [
      "Pearl of Great Price",
      "Inspired Translation",
      "Joseph Smith Translation",
      "JST",
      "Joseph Smith",
      "LDS"
    ],
    "aliases": [
      "The Book of Abraham"
    ],
    "chapterLabel": "Chapter",
    "verseLabel": "Verse",
    "authors": [
      "Abraham"
    ],
    "traditions": [],
    "dateEarliest": "07-01-1835",
    "dateLatest": "07-01-1842"
  },
  {
    "workOsisID": "PGP",
    "bookName": "Articles of Faith",
    "bookSubtitle": "of The Church of Jesus Christ of Latter-day Saints",
    "bookOsisID": "AofF",
    "paratext": null,
    "groups": [
      "Pearl of Great Price",
      "LDS",
      "Joseph Smith"
    ],
    "aliases": [
      "AofF"
    ],
    "chapterLabel": "",
    "verseLabel": "Article",
    "authors": [
      "Joseph Smith"
    ],
    "traditions": [],
    "dateEarliest": "03-01-1842",
    "dateLatest": "03-01-1842"
  },
  {
    "workOsisID": "PGP",
    "bookName": "Joseph Smith—History",
    "bookSubtitle": "Extracts from the History of Joseph Smith, the Prophet",
    "bookOsisID": "JSH",
    "paratext": null,
    "groups": [
      "Pearl of Great Price",
      "Inspired Translation",
      "Joseph Smith Translation",
      "JST",
      "Joseph Smith",
      "LDS"
    ],
    "aliases": [
      "JSH",
      "JS-H",
      "Joseph Smith History",
      "Joseph Smith--History"
    ],
    "chapterLabel": "",
    "verseLabel": "Verse",
    "authors": [
      "Joseph Smith"
    ],
    "traditions": [],
    "dateEarliest": "04-01-1838",
    "dateLatest": "04-30-1838"
  },
  {
    "workOsisID": "PGP",
    "bookName": "Joseph Smith—Matthew",
    "bookSubtitle": "An extract from the translation of the Bible as revealed to Joseph Smith the Prophet in 1831: Matthew 23:39 and chapter 24",
    "bookOsisID": "JSM",
    "paratext": null,
    "groups": [
      "Pearl of Great Price",
      "Inspired Translation",
      "Joseph Smith Translation",
      "JST",
      "Joseph Smith",
      "LDS"
    ],
    "aliases": [
      "JSM",
      "JS-M",
      "Joseph Smith Matthew",
      "Joseph Smith--Matthew"
    ],
    "chapterLabel": "",
    "verseLabel": "Verse",
    "authors": [
      "St. Matthew"
    ],
    "traditions": [],
    "dateEarliest": "03-07-1831",
    "dateLatest": "03-10-1831"
  },
  {
    "workOsisID": "D&C",
    "bookName": "D&C",
    "bookSubtitle": "of The Church of Jesus Christ of Latter-day Saints",
    "bookOsisID": "D&C",
    "paratext": null,
    "groups": [
      "Doctrine and Covenants",
      "LDS"
    ],
    "aliases": [
      "D and C",
      "The Doctrine & Covenants",
      "Doctrine & Covenants",
      "The Doctrine and Covenants"
    ],
    "chapterLabel": "Section",
    "verseLabel": "Verse",
    "authors": [
      "Joseph Smith"
    ],
    "traditions": [],
    "dateEarliest": "1823-09-21",
    "dateLatest": "1841-01-19"
  }
];
const b = books;
export const booksLookup : Record<string, (typeof b)[number]> = {
  "GENESIS": b[0],
  "GEN": b[0],
  "GE": b[0],
  "GN": b[0],
  "THE FIRST BOOK OF MOSES CALLED GENESIS": b[0],
  "EXODUS": b[1],
  "EXOD": b[1],
  "EXO": b[1],
  "EX": b[1],
  "THE SECOND BOOK OF MOSES CALLED EXODUS": b[1],
  "LEVITICUS": b[2],
  "LEV": b[2],
  "LE": b[2],
  "THE THIRD BOOK OF MOSES CALLED LEVITICUS": b[2],
  "NUMBERS": b[3],
  "NUM": b[3],
  "NU": b[3],
  "NM": b[3],
  "NB": b[3],
  "THE FOURTH BOOK OF MOSES CALLED NUMBERS": b[3],
  "DEUTERONOMY": b[4],
  "DEUT": b[4],
  "DEU": b[4],
  "DT": b[4],
  "DU": b[4],
  "THE FIFTH BOOK OF MOSES CALLED DEUTERONOMY": b[4],
  "JOSHUA": b[5],
  "JOSH": b[5],
  "JOS": b[5],
  "JUDGES": b[6],
  "JUDG": b[6],
  "JDG": b[6],
  "JDGS": b[6],
  "JG": b[6],
  "RUTH": b[7],
  "RUT": b[7],
  "RTH": b[7],
  "RU": b[7],
  "1 SAMUEL": b[8],
  "1SAM": b[8],
  "1SA": b[8],
  "1 SAM": b[8],
  "1 SM": b[8],
  "1 SA": b[8],
  "1 S": b[8],
  "I SAM": b[8],
  "I SA": b[8],
  "1S": b[8],
  "1ST SAMUEL": b[8],
  "1ST SAM": b[8],
  "FIRST SAMUEL": b[8],
  "FIRST SAM": b[8],
  "2 SAMUEL": b[9],
  "2SAM": b[9],
  "2SA": b[9],
  "2 SAM": b[9],
  "2 SM": b[9],
  "2 SA": b[9],
  "2 S": b[9],
  "II SAM": b[9],
  "II SA": b[9],
  "2S": b[9],
  "2ND SAMUEL": b[9],
  "2ND SAM": b[9],
  "SECOND SAMUEL": b[9],
  "SECOND SAM": b[9],
  "1 KINGS": b[10],
  "1KGS": b[10],
  "1KI": b[10],
  "1 KGS": b[10],
  "1 KI": b[10],
  "1KIN": b[10],
  "1K": b[10],
  "I KGS": b[10],
  "I KI": b[10],
  "1ST KINGS": b[10],
  "1ST KGS": b[10],
  "FIRST KINGS": b[10],
  "FIRST KGS": b[10],
  "2 KINGS": b[11],
  "2KGS": b[11],
  "2KI": b[11],
  "2 KGS": b[11],
  "2 KI": b[11],
  "2KIN": b[11],
  "2K": b[11],
  "II KGS": b[11],
  "II KI": b[11],
  "2ND KINGS": b[11],
  "2ND KGS": b[11],
  "SECOND KINGS": b[11],
  "SECOND KGS": b[11],
  "1 CHRONICLES": b[12],
  "1CHR": b[12],
  "1CH": b[12],
  "1 CHRON": b[12],
  "1 CHR": b[12],
  "1 CH": b[12],
  "1CHRON": b[12],
  "I CHRON": b[12],
  "I CHR": b[12],
  "I CH": b[12],
  "1ST CHRONICLES": b[12],
  "1ST CHRON": b[12],
  "FIRST CHRONICLES": b[12],
  "FIRST CHRON": b[12],
  "2 CHRONICLES": b[13],
  "2CHR": b[13],
  "2CH": b[13],
  "2 CHRON": b[13],
  "2 CHR": b[13],
  "2 CH": b[13],
  "2CHRON": b[13],
  "II CHRON": b[13],
  "II CHR": b[13],
  "II CH": b[13],
  "2ND CHRONICLES": b[13],
  "2ND CHRON": b[13],
  "SECOND CHRONICLES": b[13],
  "SECOND CHRON": b[13],
  "EZRA": b[14],
  "EZR": b[14],
  "EZ": b[14],
  "NEHEMIAH": b[15],
  "NEH": b[15],
  "NE": b[15],
  "ESTHER": b[16],
  "ESTH": b[16],
  "EST": b[16],
  "ES": b[16],
  "JOB": b[17],
  "JB": b[17],
  "PSALMS": b[18],
  "PS": b[18],
  "PSA": b[18],
  "PSALM": b[18],
  "PSLM": b[18],
  "PSM": b[18],
  "PSS": b[18],
  "PROVERBS": b[19],
  "PROV": b[19],
  "PRO": b[19],
  "PRV": b[19],
  "PV": b[19],
  "ECCLESIASTES": b[20],
  "ECCL": b[20],
  "ECC": b[20],
  "QOHELET": b[20],
  "SONG OF SOLOMON": b[21],
  "SONG": b[21],
  "SNG": b[21],
  "CANTICLE OF CANTICLES": b[21],
  "SOLOMON'S SONG": b[21],
  "ISAIAH": b[22],
  "ISA": b[22],
  "IS": b[22],
  "JEREMIAH": b[23],
  "JER": b[23],
  "JE": b[23],
  "JR": b[23],
  "LAMENTATIONS": b[24],
  "LAM": b[24],
  "LA": b[24],
  "EZEKIEL": b[25],
  "EZEK": b[25],
  "EZK": b[25],
  "DANIEL": b[26],
  "DAN": b[26],
  "DA": b[26],
  "DN": b[26],
  "HOSEA": b[27],
  "HOS": b[27],
  "HO": b[27],
  "JOEL": b[28],
  "JOL": b[28],
  "JL": b[28],
  "AMOS": b[29],
  "AMO": b[29],
  "AM": b[29],
  "OBADIAH": b[30],
  "OBAD": b[30],
  "OBA": b[30],
  "OB": b[30],
  "JONAH": b[31],
  "JON": b[31],
  "MICAH": b[32],
  "MIC": b[32],
  "MC": b[32],
  "NAHUM": b[33],
  "NAH": b[33],
  "NAM": b[33],
  "NH": b[33],
  "NHM": b[33],
  "HABAKKUK": b[34],
  "HAB": b[34],
  "HB": b[34],
  "ZEPHANIAH": b[35],
  "ZEPH": b[35],
  "ZEP": b[35],
  "ZP": b[35],
  "HAGGAI": b[36],
  "HAG": b[36],
  "HG": b[36],
  "HGI": b[36],
  "HAGI": b[36],
  "ZECHARIAH": b[37],
  "ZECH": b[37],
  "ZEC": b[37],
  "ZC": b[37],
  "MALACHI": b[38],
  "MAL": b[38],
  "ML": b[38],
  "MATTHEW": b[39],
  "MATT": b[39],
  "MAT": b[39],
  "ST MATTHEW": b[39],
  "ST. MATTHEW": b[39],
  "SAINT MATTHEW": b[39],
  "THE GOSPEL ACCORDING TO ST MATTHEW": b[39],
  "THE GOSPEL ACCORDING TO ST. MATTHEW": b[39],
  "THE GOSPEL ACCORDING TO SAINT MATTHEW": b[39],
  "MARK": b[40],
  "MRK": b[40],
  "ST MARK": b[40],
  "ST. MARK": b[40],
  "SAINT MARK": b[40],
  "THE GOSPEL ACCORDING TO ST MARK": b[40],
  "THE GOSPEL ACCORDING TO ST. MARK": b[40],
  "THE GOSPEL ACCORDING TO SAINT MARK": b[40],
  "LUKE": b[41],
  "LUK": b[41],
  "ST LUKE": b[41],
  "ST. LUKE": b[41],
  "SAINT LUKE": b[41],
  "THE GOSPEL ACCORDING TO ST LUKE": b[41],
  "THE GOSPEL ACCORDING TO ST. LUKE": b[41],
  "THE GOSPEL ACCORDING TO SAINT LUKE": b[41],
  "JOHN": b[42],
  "JHN": b[42],
  "ST JOHN": b[42],
  "ST. JOHN": b[42],
  "SAINT JOHN": b[42],
  "THE GOSPEL ACCORDING TO ST JOHN": b[42],
  "THE GOSPEL ACCORDING TO ST. JOHN": b[42],
  "THE GOSPEL ACCORDING TO SAINT JOHN": b[42],
  "ACTS": b[43],
  "ACT": b[43],
  "AC": b[43],
  "ROMANS": b[44],
  "ROM": b[44],
  "RO": b[44],
  "RM": b[44],
  "1 CORINTHIANS": b[45],
  "1COR": b[45],
  "1CO": b[45],
  "1 COR": b[45],
  "1 CO": b[45],
  "I COR": b[45],
  "I CO": b[45],
  "I CORINTHIANS": b[45],
  "1CORINTHIANS": b[45],
  "1ST CORINTHIANS": b[45],
  "FIRST CORINTHIANS": b[45],
  "2 CORINTHIANS": b[46],
  "2COR": b[46],
  "2CO": b[46],
  "2 COR": b[46],
  "2 CO": b[46],
  "II COR": b[46],
  "II CO": b[46],
  "II CORINTHIANS": b[46],
  "2CORINTHIANS": b[46],
  "2ND CORINTHIANS": b[46],
  "SECOND CORINTHIANS": b[46],
  "GALATIANS": b[47],
  "GAL": b[47],
  "GA": b[47],
  "EPHESIANS": b[48],
  "EPH": b[48],
  "EPHES": b[48],
  "EP": b[48],
  "PHILIPPIANS": b[49],
  "PHIL": b[49],
  "PHP": b[49],
  "PP": b[49],
  "COLOSSIANS": b[50],
  "COL": b[50],
  "CO": b[50],
  "1 THESSALONIANS": b[51],
  "1THESS": b[51],
  "1TH": b[51],
  "1 THESS": b[51],
  "1 THES": b[51],
  "1 TH": b[51],
  "I THESSALONIANS": b[51],
  "I THESS": b[51],
  "I THES": b[51],
  "I TH": b[51],
  "1THESSALONIANS": b[51],
  "1THES": b[51],
  "1ST THESSALONIANS": b[51],
  "1ST THESS": b[51],
  "FIRST THESSALONIANS": b[51],
  "FIRST THESS": b[51],
  "2 THESSALONIANS": b[52],
  "2THESS": b[52],
  "2TH": b[52],
  "2 THESS": b[52],
  "2 THES": b[52],
  "2 TH": b[52],
  "II THESSALONIANS": b[52],
  "II THESS": b[52],
  "II THES": b[52],
  "II TH": b[52],
  "2THESSALONIANS": b[52],
  "2THES": b[52],
  "2ND THESSALONIANS": b[52],
  "2ND THESS": b[52],
  "SECOND THESSALONIANS": b[52],
  "SECOND THESS": b[52],
  "1 TIMOTHY": b[53],
  "1TIM": b[53],
  "1TI": b[53],
  "1 TIM": b[53],
  "1 TI": b[53],
  "I TIMOTHY": b[53],
  "I TIM": b[53],
  "I TI": b[53],
  "1TIMOTHY": b[53],
  "1ST TIMOTHY": b[53],
  "1ST TIM": b[53],
  "FIRST TIMOTHY": b[53],
  "FIRST TIM": b[53],
  "2 TIMOTHY": b[54],
  "2TIM": b[54],
  "2TI": b[54],
  "2 TIM": b[54],
  "2 TI": b[54],
  "II TIMOTHY": b[54],
  "II TIM": b[54],
  "II TI": b[54],
  "2TIMOTHY": b[54],
  "2ND TIMOTHY": b[54],
  "2ND TIM": b[54],
  "SECOND TIMOTHY": b[54],
  "SECOND TIM": b[54],
  "TITUS": b[55],
  "TIT": b[55],
  "TI": b[55],
  "TTS": b[55],
  "PHILEMON": b[56],
  "PHLM": b[56],
  "PHM": b[56],
  "PM": b[56],
  "HEBREWS": b[57],
  "HEB": b[57],
  "JAMES": b[58],
  "JAS": b[58],
  "JM": b[58],
  "1 PETER": b[59],
  "1PET": b[59],
  "1PE": b[59],
  "1 PET": b[59],
  "1 PE": b[59],
  "1 PT": b[59],
  "1 P": b[59],
  "I PET": b[59],
  "I PT": b[59],
  "I PE": b[59],
  "1PETER": b[59],
  "1PT": b[59],
  "1P": b[59],
  "I PETER": b[59],
  "1ST PETER": b[59],
  "FIRST PETER": b[59],
  "2 PETER": b[60],
  "2PET": b[60],
  "2PE": b[60],
  "2 PET": b[60],
  "2 PE": b[60],
  "2 PT": b[60],
  "2 P": b[60],
  "II PETER": b[60],
  "II PET": b[60],
  "II PT": b[60],
  "II PE": b[60],
  "2PETER": b[60],
  "2PT": b[60],
  "2P": b[60],
  "2ND PETER": b[60],
  "SECOND PETER": b[60],
  "1 JOHN": b[61],
  "1JOHN": b[61],
  "1JN": b[61],
  "1 JHN": b[61],
  "1 JN": b[61],
  "1 J": b[61],
  "1JHN": b[61],
  "1JOH": b[61],
  "1JO": b[61],
  "1J": b[61],
  "I JOHN": b[61],
  "I JHN": b[61],
  "I JOH": b[61],
  "I JN": b[61],
  "I JO": b[61],
  "1ST JOHN": b[61],
  "FIRST JOHN": b[61],
  "2 JOHN": b[62],
  "2JOHN": b[62],
  "2JN": b[62],
  "2 JHN": b[62],
  "2 JN": b[62],
  "2 J": b[62],
  "2JHN": b[62],
  "2JOH": b[62],
  "2JO": b[62],
  "2J": b[62],
  "II JOHN": b[62],
  "II JHN": b[62],
  "II JOH": b[62],
  "II JN": b[62],
  "II JO": b[62],
  "2ND JOHN": b[62],
  "SECOND JOHN": b[62],
  "3 JOHN": b[63],
  "3JOHN": b[63],
  "3JN": b[63],
  "3 JHN": b[63],
  "3 JN": b[63],
  "3 J": b[63],
  "3JHN": b[63],
  "3JOH": b[63],
  "3JO": b[63],
  "3J": b[63],
  "III JOHN": b[63],
  "III JHN": b[63],
  "III JOH": b[63],
  "III JN": b[63],
  "III JO": b[63],
  "3RD JOHN": b[63],
  "THIRD JOHN": b[63],
  "JUDE": b[64],
  "JUD": b[64],
  "JD": b[64],
  "REVELATION": b[65],
  "REV": b[65],
  "RE": b[65],
  "THE REVELATION": b[65],
  "TOBIT": b[66],
  "TOB": b[66],
  "JUDITH": b[67],
  "JDT": b[67],
  "ADDITIONS TO ESTHER": b[68],
  "ADDESTH": b[68],
  "ADE": b[68],
  "WISDOM": b[69],
  "WIS": b[69],
  "WISDOM OF SOLOMON": b[69],
  "SIRACH PROLOGUE": b[70],
  "SIRP": b[70],
  "ECCLESIASTICUS PROLOGUE": b[70],
  "SIRACH": b[71],
  "SIR": b[71],
  "ECCLESIASTICUS": b[71],
  "PRAYER OF AZARIAH": b[72],
  "PRAZAR": b[72],
  "S3Y": b[72],
  "SONG OF THE THREE CHILDREN": b[72],
  "SONG OF THE THREE HOLY CHILDREN": b[72],
  "SUSANNA": b[73],
  "SUS": b[73],
  "1 MACCABEES": b[74],
  "1MACC": b[74],
  "1MA": b[74],
  "2 MACCABEES": b[75],
  "2MACC": b[75],
  "2MA": b[75],
  "PRAYER OF MANASSEH": b[76],
  "PRMAN": b[76],
  "MAN": b[76],
  "1 ESDRAS": b[77],
  "1ESD": b[77],
  "1ES": b[77],
  "2 ESDRAS": b[78],
  "2ESD": b[78],
  "2ES": b[78],
  "EPISTLE TO THE LAODICEANS": b[79],
  "EPLAO": b[79],
  "LAO": b[79],
  "LAODICEANS": b[79],
  "DIDACHE": b[80],
  "DID": b[80],
  "1 NEPHI": b[81],
  "1NE": b[81],
  "1 NE": b[81],
  "1ST NEPHI": b[81],
  "FIRST NEPHI": b[81],
  "THE FIRST BOOK OF NEPHI": b[81],
  "I NEPHI": b[81],
  "2 NEPHI": b[82],
  "2NE": b[82],
  "2 NE": b[82],
  "2ND NEPHI": b[82],
  "SECOND NEPHI": b[82],
  "THE SECOND BOOK OF NEPHI": b[82],
  "II NEPHI": b[82],
  "JACOB": b[83],
  "JAC": b[83],
  "ENOS": b[84],
  "JAROM": b[85],
  "JAR": b[85],
  "OMNI": b[86],
  "WORDS OF MORMON": b[87],
  "WOM": b[87],
  "MOSIAH": b[88],
  "MOSI": b[88],
  "ALMA": b[89],
  "HELAMAN": b[90],
  "HEL": b[90],
  "HE": b[90],
  "HLM": b[90],
  "HELM": b[90],
  "3 NEPHI": b[91],
  "3NE": b[91],
  "3 NE": b[91],
  "3RD NEPHI": b[91],
  "THIRD NEPHI": b[91],
  "III NEPHI": b[91],
  "4 NEPHI": b[92],
  "4NE": b[92],
  "4 NE": b[92],
  "4TH NEPHI": b[92],
  "FOURTH NEPHI": b[92],
  "IV NEPHI": b[92],
  "MORMON": b[93],
  "MORM": b[93],
  "MMN": b[93],
  "ETHER": b[94],
  "ETH": b[94],
  "MORONI": b[95],
  "MORO": b[95],
  "MNI": b[95],
  "MOSES": b[96],
  "MOS": b[96],
  "THE BOOK OF MOSES": b[96],
  "ABRAHAM": b[97],
  "ABR": b[97],
  "THE BOOK OF ABRAHAM": b[97],
  "ARTICLES OF FAITH": b[98],
  "AOFF": b[98],
  "JOSEPH SMITH—HISTORY": b[99],
  "JSH": b[99],
  "JS-H": b[99],
  "JOSEPH SMITH HISTORY": b[99],
  "JOSEPH SMITH--HISTORY": b[99],
  "JOSEPH SMITH—MATTHEW": b[100],
  "JSM": b[100],
  "JS-M": b[100],
  "JOSEPH SMITH MATTHEW": b[100],
  "JOSEPH SMITH--MATTHEW": b[100],
  "D&C": b[101],
  "D AND C": b[101],
  "THE DOCTRINE & COVENANTS": b[101],
  "DOCTRINE & COVENANTS": b[101],
  "THE DOCTRINE AND COVENANTS": b[101],
};
export const groupsLookup : Record<string, BookShape[]> = {
  "OLD TESTAMENT": [
    b[0],
    b[1],
    b[2],
    b[3],
    b[4],
    b[5],
    b[6],
    b[7],
    b[8],
    b[9],
    b[10],
    b[11],
    b[12],
    b[13],
    b[14],
    b[15],
    b[16],
    b[17],
    b[18],
    b[19],
    b[20],
    b[21],
    b[22],
    b[23],
    b[24],
    b[25],
    b[26],
    b[27],
    b[28],
    b[29],
    b[30],
    b[31],
    b[32],
    b[33],
    b[34],
    b[35],
    b[36],
    b[37],
    b[38],
  ],
  "HEBREW BIBLE": [
    b[0],
    b[1],
    b[2],
    b[3],
    b[4],
    b[5],
    b[6],
    b[7],
    b[8],
    b[9],
    b[10],
    b[11],
    b[12],
    b[13],
    b[14],
    b[15],
    b[16],
    b[17],
    b[18],
    b[19],
    b[20],
    b[21],
    b[22],
    b[23],
    b[24],
    b[25],
    b[26],
    b[27],
    b[28],
    b[29],
    b[30],
    b[31],
    b[32],
    b[33],
    b[34],
    b[35],
    b[36],
    b[37],
    b[38],
  ],
  "BIBLE": [
    b[0],
    b[1],
    b[2],
    b[3],
    b[4],
    b[5],
    b[6],
    b[7],
    b[8],
    b[9],
    b[10],
    b[11],
    b[12],
    b[13],
    b[14],
    b[15],
    b[16],
    b[17],
    b[18],
    b[19],
    b[20],
    b[21],
    b[22],
    b[23],
    b[24],
    b[25],
    b[26],
    b[27],
    b[28],
    b[29],
    b[30],
    b[31],
    b[32],
    b[33],
    b[34],
    b[35],
    b[36],
    b[37],
    b[38],
    b[39],
    b[40],
    b[41],
    b[42],
    b[43],
    b[44],
    b[45],
    b[46],
    b[47],
    b[48],
    b[49],
    b[50],
    b[51],
    b[52],
    b[53],
    b[54],
    b[55],
    b[56],
    b[57],
    b[58],
    b[59],
    b[60],
    b[61],
    b[62],
    b[63],
    b[64],
    b[65],
  ],
  "PENTATUECH": [
    b[0],
    b[1],
    b[2],
    b[3],
  ],
  "TORAH": [
    b[0],
    b[1],
    b[2],
    b[3],
  ],
  "KINGS": [
    b[10],
    b[11],
  ],
  "PERSIAN PERIOD": [
    b[12],
    b[13],
    b[14],
    b[15],
  ],
  "NEW TESTAMENT": [
    b[39],
    b[40],
    b[41],
    b[42],
    b[43],
    b[44],
    b[45],
    b[46],
    b[47],
    b[48],
    b[49],
    b[50],
    b[51],
    b[52],
    b[53],
    b[54],
    b[55],
    b[56],
    b[57],
    b[58],
    b[59],
    b[60],
    b[61],
    b[62],
    b[63],
    b[64],
    b[65],
  ],
  "GOSPELS": [
    b[39],
    b[40],
    b[41],
    b[42],
  ],
  "PAULINE EPISTLES": [
    b[44],
    b[45],
    b[46],
    b[47],
    b[48],
    b[49],
    b[50],
    b[51],
    b[52],
    b[53],
    b[54],
    b[55],
    b[56],
  ],
  "DEUTEROCANNON": [
    b[66],
    b[67],
    b[68],
    b[69],
    b[70],
    b[71],
    b[72],
    b[73],
    b[74],
    b[75],
    b[76],
    b[77],
    b[78],
  ],
  "APOCRYPHA": [
    b[66],
    b[67],
    b[68],
    b[69],
    b[70],
    b[71],
    b[72],
    b[73],
    b[74],
    b[75],
    b[76],
    b[77],
    b[78],
    b[79],
    b[80],
  ],
  "VULGATE": [
    b[79],
  ],
  "APOSTOLIC FATHERS": [
    b[80],
  ],
  "BOOK OF MORMON": [
    b[81],
    b[82],
    b[83],
    b[84],
    b[85],
    b[86],
    b[87],
    b[88],
    b[89],
    b[90],
    b[91],
    b[92],
    b[93],
    b[94],
    b[95],
  ],
  "SMALL PLATES OF NEPHI": [
    b[81],
    b[82],
    b[83],
    b[84],
    b[85],
    b[86],
  ],
  "LDS": [
    b[81],
    b[82],
    b[83],
    b[84],
    b[85],
    b[86],
    b[87],
    b[88],
    b[89],
    b[90],
    b[91],
    b[92],
    b[93],
    b[94],
    b[95],
    b[96],
    b[97],
    b[98],
    b[99],
    b[100],
    b[101],
  ],
  "MORMON": [
    b[87],
    b[88],
    b[89],
    b[90],
    b[91],
    b[92],
    b[93],
    b[94],
    b[95],
  ],
  "LARGE PLATES OF NEPHI": [
    b[88],
    b[89],
    b[90],
    b[91],
    b[92],
    b[93],
    b[94],
    b[95],
  ],
  "ABRIDGEMENT": [
    b[88],
    b[89],
    b[90],
    b[91],
    b[92],
    b[93],
    b[94],
    b[95],
  ],
  "PEARL OF GREAT PRICE": [
    b[96],
    b[97],
    b[98],
    b[99],
    b[100],
  ],
  "INSPIRED TRANSLATION": [
    b[96],
    b[97],
    b[99],
    b[100],
  ],
  "JOSEPH SMITH TRANSLATION": [
    b[96],
    b[97],
    b[99],
    b[100],
  ],
  "JST": [
    b[96],
    b[97],
    b[99],
    b[100],
  ],
  "JOSEPH SMITH": [
    b[96],
    b[97],
    b[98],
    b[99],
    b[100],
  ],
  "DOCTRINE AND COVENANTS": [
    b[101],
  ],
};
for (const book of books) {
  const work = worksLookup[book.bookOsisID];
  // @ts-expect-error Can't add above because these values are cyclical
  if (!work.books) {
    // @ts-expect-error Can't add above because these values are cyclical
    work.books = [];
  }
  // @ts-expect-error Can't add above because these values are cyclical
  work.books.push(book);
  // @ts-expect-error Can't add above because these values are cyclical
  books.work = work;
}
for (const work of works) {
  // @ts-expect-error Can't add above because these values are cyclical
  work.bookCount = work.books.length;
}